---
- name: copy filebeat.deb
  copy:
    src: filebeat-8.6.2-amd64.deb
    dest: /home/gurov

- name: install filebeat
  apt:
    deb: "/home/gurov/filebeat-8.6.2-amd64.deb"

- name: replace config file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - enable filebeat

- name: setup filebeat
  shell: 'filebeat setup'

- name: Edit service filebeat/nginx
  template:
    src: modules.d/nginx.yml.j2
    dest: /etc/filebeat/modules.d/nginx.yml

- name: Edit service filebeat/nginx
  template:
    src: modules.d/system.yml.j2
    dest: /etc/filebeat/modules.d/system.yml

- name: Start service filebeat
  ansible.builtin.service:
    name: filebeat.service
    state: restarted
