#cloud-config
users:
 - name: ansible
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMf7dpd1leJTwyOGvY0l14laOMM52ClRz2SfvScVoort

disable_root: true
timezone: Europe/Omsk
repo_update: true
repo_upgrade: true

dnf:
  preserve_sourses_list: true

packages:
  - wget
  - nginx

runcmd:
 - [sh, -c, "sudo wget -P /tmp/ https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/download/prometheus-nginxlog-exporter_1.10.0_linux_amd64.rpm"]
 - [sh, -c, "sudo dnf -y install  /tmp/prometheus-nginxlog-exporter_1.10.0_linux_amd64.rpm"]
 - [sh, -c, "sudo wget -P /etc/systemd/system/ https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/config/prometheus-nginxlog-exporter.service"]
 - [sh, -c, "sudo wget -P /etc/ https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/config/nginxlog_exporter.yml"]
 - [sh, -c, "sudo wget -P /etc/systemd/system/ https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/config/node_exporter.service"]
 - [sh, -c, "sudo wget -P /tmp/ https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/download/node_exporter-1.6.0.linux-amd64.tar.gz"]
 - [sh, -c, "sudo tar xvf /tmp/node_exporter-1.6.0.linux-amd64.tar.gz"]
 - [sh, -c, "sudo cp -r /node_exporter-1.6.0.linux-amd64/node_exporter /usr/local/bin"]
 - [sh, -c, "sudo useradd --no-create-home --shell /bin/false node_exporter"]
 - [sh, -c, "sudo wget -P /tmp/  https://www.dropbox.com/s/dfmld6z73f83t7v/filebeat-8.6.2-x86_64.rpm"]
 - [sh, -c, "sudo dnf -y install  /tmp/filebeat-8.6.2-x86_64.rpm"]
 - [sh, -c, "sudo mv /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.bak"]
 - [sh, -c, "sudo wget -P /etc/filebeat https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/config/filebeat.yml"]
 - [sh, -c, "sudo wget -P /usr/share/nginx/html https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/config/site.tar"]
 - [sh, -c, "sudo mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.bak"]
 - [sh, -c, "sudo tar xvf /usr/share/nginx/html/site.tar -C /usr/share/nginx/html/"]
 - [sh, -c, "sudo chmod +r -R /usr/share/nginx/html/*"]
 - [sh, -c, "sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak"]
 - [sh, -c, "sudo wget -P /etc/nginx/ https://github.com/AfterHero/sys-diplom-gurovpp/blob/main/config/nginx.conf"]
 - [sh, -c, "sudo chmod +r /etc/nginx/nginx.conf"]

 - [systemctl, enable, filebeat.service]
 - [systemctl, enable, nginx.service]
 - [systemctl, start, --no-block, nginx.service]
#- [sh, -c, "echo 'Welcome to web server '$(hostname | cut -d '.' -f 1 ) > /usr/share/nginx/html/index.html"]
 - [systemctl, restart, nginx.service]
 - [systemctl, start, --no-block, node_exporter.service]
 - [systemctl, start, --no-block, prometheus-nginxlog-exporter.service]
 - [systemctl, start, --no-block, filebeat.service]
